-- ==========================================================
-- Svelte Hub - Supabase Database Schema, RBAC, & Seeders
-- ==========================================================
-- Jalankan skrip ini di SQL Editor dashboard Supabase Anda.

-- Aktifkan ekstensi pgcrypto untuk enkripsi bcrypt di schema extensions
create extension if not exists "pgcrypto" with schema extensions;
set search_path to public, extensions;

-- 1. TABEL: roles (Role-Based Access Control)
create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_debug boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by text default 'system',
  updated_by text default 'system'
);

-- 2. TABEL: users (Data Pengguna)
create table if not exists public.users (
  uuid uuid primary key default gen_random_uuid(),
  username text not null unique,
  name text not null,
  password text not null,
  role_id bigint references public.roles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by text default 'system',
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_by text default 'system'
);

-- 3. TABEL: apps (List Aplikasi Hub)
create table if not exists public.apps (
  id text primary key,
  name text not null,
  description text not null,
  url text not null,
  icon text not null default '⚡',
  category text not null default 'General',
  color text not null default 'var(--color-nb-yellow)',
  pic_name text not null,
  pic_whatsapp text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. TABEL: todos (To-Do List Utama)
create table if not exists public.todos (
  id text primary key,
  "appId" text references public.apps(id) on delete cascade,
  text text not null,
  done boolean not null default false,
  created_at bigint not null
);

-- Migrasi jika kolom sebelumnya adalah app_id (snake_case)
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'todos' and column_name = 'app_id'
  ) then
    alter table public.todos rename column app_id to "appId";
  end if;
end $$;

-- 5. TABEL: subtodos (Subtask terpisah yang berelasi dengan todos)
create table if not exists public.subtodos (
  id text primary key,
  todo_id text not null references public.todos(id) on delete cascade,
  text text not null,
  done boolean not null default false,
  created_at bigint not null
);

-- Indexes
create index if not exists idx_todos_appid on public.todos("appId");
create index if not exists idx_subtodos_todo_id on public.subtodos(todo_id);
create index if not exists idx_users_username on public.users(username);

-- 6. RPC: Autentikasi User (Verifikasi Bcrypt aman di sisi database)
create or replace function public.authenticate_user(
  p_username text,
  p_password text
)
returns table (
  uuid uuid,
  username text,
  name text,
  role_id bigint,
  role_name text,
  is_debug boolean
)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  return query
  select
    u.uuid,
    u.username,
    u.name,
    u.role_id,
    r.name as role_name,
    coalesce(r.is_debug, false) as is_debug
  from public.users u
  left join public.roles r on u.role_id = r.id
  where u.username = p_username
    and u.password = crypt(p_password, u.password)
  limit 1;
end;
$$;

-- 7. ROW LEVEL SECURITY (RLS)
alter table public.roles enable row level security;
alter table public.users enable row level security;
alter table public.apps enable row level security;
alter table public.todos enable row level security;
alter table public.subtodos enable row level security;

-- Policies: apps
drop policy if exists "Allow public read access to apps" on public.apps;
create policy "Allow public read access to apps"
  on public.apps for select
  to anon, authenticated
  using (true);

drop policy if exists "Allow public write access to apps" on public.apps;
create policy "Allow public write access to apps"
  on public.apps for all
  to anon, authenticated
  using (true)
  with check (true);

-- Policies: todos
drop policy if exists "Allow public access to todos" on public.todos;
create policy "Allow public access to todos"
  on public.todos for all
  to anon, authenticated
  using (true)
  with check (true);

-- Policies: subtodos
drop policy if exists "Allow public access to subtodos" on public.subtodos;
create policy "Allow public access to subtodos"
  on public.subtodos for all
  to anon, authenticated
  using (true)
  with check (true);

-- Policies: roles & users
drop policy if exists "Allow public read roles" on public.roles;
create policy "Allow public read roles"
  on public.roles for select
  to anon, authenticated
  using (true);

-- 8. SEED DATA AWAL: Roles & Default Superadmin User
insert into public.roles (id, name, is_debug, created_at, updated_at, created_by, updated_by)
values (
  1,
  'SUPERADMIN',
  true,
  timezone('utc'::text, now()),
  timezone('utc'::text, now()),
  'system',
  'system'
)
on conflict (id) do update
set
  name = excluded.name,
  is_debug = excluded.is_debug,
  updated_at = timezone('utc'::text, now());

select setval(pg_get_serial_sequence('public.roles', 'id'), coalesce(max(id), 1)) from public.roles;

insert into public.users (
  uuid,
  username,
  name,
  password,
  role_id,
  created_at,
  created_by,
  updated_at,
  updated_by
)
values (
  'a0000000-0000-0000-0000-000000000001',
  'rizlfauzy',
  'Rizal Fauzi',
  extensions.crypt('admin123', extensions.gen_salt('bf', 10)),
  1,
  timezone('utc'::text, now()),
  'system',
  timezone('utc'::text, now()),
  'system'
)
on conflict (username) do update
set
  name = excluded.name,
  password = excluded.password,
  role_id = excluded.role_id,
  updated_at = timezone('utc'::text, now());

-- 9. SEED ROLE: VIEWER (Role default untuk pendaftar baru)
insert into public.roles (id, name, is_debug, created_at, updated_at, created_by, updated_by)
values (
  2,
  'VIEWER',
  false,
  timezone('utc'::text, now()),
  timezone('utc'::text, now()),
  'system',
  'system'
)
on conflict (name) do update
set
  is_debug = false,
  updated_at = timezone('utc'::text, now());

select setval(pg_get_serial_sequence('public.roles', 'id'), coalesce(max(id), 1)) from public.roles;

-- 10. RPC: Register User (Registrasi User Baru sebagai VIEWER dengan password bcrypt)
create or replace function public.register_user(
  p_username text,
  p_name text,
  p_password text
)
returns table (
  uuid uuid,
  username text,
  name text,
  role_id bigint,
  role_name text,
  is_debug boolean
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_role_id bigint;
  v_role_name text;
  v_is_debug boolean;
  v_new_uuid uuid;
  v_clean_username text;
  v_clean_name text;
begin
  v_clean_username := lower(trim(p_username));
  v_clean_name := trim(p_name);

  if coalesce(v_clean_username, '') = '' then
    raise exception 'Username wajib diisi!';
  end if;
  if coalesce(v_clean_name, '') = '' then
    raise exception 'Nama lengkap wajib diisi!';
  end if;
  if coalesce(p_password, '') = '' or length(p_password) < 6 then
    raise exception 'Password minimal 6 karakter!';
  end if;

  if exists (select 1 from public.users where lower(users.username) = v_clean_username) then
    raise exception 'Username sudah digunakan!';
  end if;

  select id, name, is_debug into v_role_id, v_role_name, v_is_debug
  from public.roles
  where upper(roles.name) = 'VIEWER'
  limit 1;

  if v_role_id is null then
    insert into public.roles (name, is_debug, created_by, updated_by)
    values ('VIEWER', false, 'system', 'system')
    returning id, name, is_debug into v_role_id, v_role_name, v_is_debug;
  end if;

  insert into public.users (
    username,
    name,
    password,
    role_id,
    created_at,
    created_by,
    updated_at,
    updated_by
  )
  values (
    v_clean_username,
    v_clean_name,
    crypt(p_password, gen_salt('bf', 10)),
    v_role_id,
    timezone('utc'::text, now()),
    'register',
    timezone('utc'::text, now()),
    'register'
  )
  returning users.uuid into v_new_uuid;

  return query
  select
    v_new_uuid,
    v_clean_username,
    v_clean_name,
    v_role_id,
    v_role_name,
    coalesce(v_is_debug, false);
end;
$$;

