-- ==========================================================
-- Migration: 20260923000001_create_tables.sql
-- Create roles, users, apps, todos, subtodos tables & RLS
-- ==========================================================

-- Enable pgcrypto for secure bcrypt password hashing in Supabase extensions schema
create extension if not exists "pgcrypto" with schema extensions;

-- Pastikan search_path mencakup public dan extensions
set search_path to public, extensions;

-- 1. TABEL: roles (Manajemen Hak Akses / RBAC)
create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_debug boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by text default 'system',
  updated_by text default 'system'
);

-- 2. TABEL: users (Pengguna Aplikasi)
create table if not exists public.users (
  uuid uuid primary key default gen_random_uuid(),
  username text not null unique,
  name text not null,
  password text not null,
  role_id bigint references public.roles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by text default 'system',
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_by text default 'system'
);

-- 3. TABEL: apps (Daftar Aplikasi Hub)
create table if not exists public.apps (
  id text primary key,
  name text not null,
  description text not null,
  url text not null,
  icon text not null default '⚡',
  category text not null default 'General',
  color text not null default 'var(--color-nb-yellow)',
  pic_name text not null,
  pic_whatsapp text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. TABEL: todos (Catatan & To-Do List Utama)
create table if not exists public.todos (
  id text primary key,
  "appId" text references public.apps(id) on delete cascade,
  text text not null,
  done boolean not null default false,
  created_at bigint not null
);

-- 5. TABEL: subtodos (Subtask Berelasi dengan todos)
create table if not exists public.subtodos (
  id text primary key,
  todo_id text not null references public.todos(id) on delete cascade,
  text text not null,
  done boolean not null default false,
  created_at bigint not null
);

-- Index untuk performa join & lookup
create index if not exists idx_todos_appid on public.todos("appId");
create index if not exists idx_subtodos_todo_id on public.subtodos(todo_id);
create index if not exists idx_users_username on public.users(username);

-- 6. RPC: Autentikasi User Aman (Verifikasi Bcrypt tanpa mengekspos hash)
create or replace function public.authenticate_user(
  p_username text,
  p_password text
)
returns table (
  uuid uuid,
  username text,
  name text,
  role_id bigint,
  role_name text,
  is_debug boolean
)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  return query
  select
    u.uuid,
    u.username,
    u.name,
    u.role_id,
    r.name as role_name,
    coalesce(r.is_debug, false) as is_debug
  from public.users u
  left join public.roles r on u.role_id = r.id
  where u.username = p_username
    and u.password = crypt(p_password, u.password)
  limit 1;
end;
$$;

-- 7. ROW LEVEL SECURITY (RLS)
alter table public.roles enable row level security;
alter table public.users enable row level security;
alter table public.apps enable row level security;
alter table public.todos enable row level security;
alter table public.subtodos enable row level security;

-- Policies: apps (Public Read, Manageable via app/anon for demo)
drop policy if exists "Allow public read access to apps" on public.apps;
create policy "Allow public read access to apps"
  on public.apps for select
  to anon, authenticated
  using (true);

drop policy if exists "Allow public write access to apps" on public.apps;
create policy "Allow public write access to apps"
  on public.apps for all
  to anon, authenticated
  using (true)
  with check (true);

-- Policies: todos (Public Read & Write)
drop policy if exists "Allow public access to todos" on public.todos;
create policy "Allow public access to todos"
  on public.todos for all
  to anon, authenticated
  using (true)
  with check (true);

-- Policies: subtodos (Public Read & Write)
drop policy if exists "Allow public access to subtodos" on public.subtodos;
create policy "Allow public access to subtodos"
  on public.subtodos for all
  to anon, authenticated
  using (true)
  with check (true);

-- Policies: roles & users (Read only via authenticated or RPC)
drop policy if exists "Allow public read roles" on public.roles;
create policy "Allow public read roles"
  on public.roles for select
  to anon, authenticated
  using (true);
